############################################################
# Render Blueprint for deploying Open WebUI                #
#                                                          #
# Docs: https://render.com/docs/blueprint-spec             #
# Deploy: render blueprint launch                          #
#                                                          #
# Notes:                                                   #
# - Uses the multi-stage Dockerfile in repo.               #
# - Exposes port 8080 (default in Dockerfile).             #
# - Persists data folder (backend/data) on a Render Disk.  #
# - Set secrets in the Render dashboard or via blueprint.  #
# - WEBUI_SECRET_KEY should be a secret.                   #
# - Toggle embedded Ollama by setting USE_OLLAMA=true.     #
# - GPU instances are limited; omit gpuType if not needed. #
# - To enable CUDA builds set build args & choose GPU plan.#
############################################################

services:
  - type: web
    name: open-webui
    env: docker
    plan: standard # starter | standard | pro
    region: oregon # choose closest
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    build:
      dockerCommand: ''
      args:
        USE_SLIM: 'true'  # faster startup, skip pre-downloading models
        USE_EMBEDDING_MODEL: 'sentence-transformers/all-MiniLM-L6-v2'
    autoDeploy: true
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
      targetCPUPercent: 60
    envVars:
      - key: PORT
        value: '8080'
      - key: WEBUI_SECRET_KEY
        generateValue: true
      # Database (set DATABASE_URL in dashboard; leave blank here to avoid committing secrets)
      - key: DATABASE_URL
        sync: false
      # Optional: tighten CORS for production
      - key: CORS_ALLOW_ORIGIN
        value: 'https://open-webui-ivanmd.onrender.com'
      - key: ANONYMIZED_TELEMETRY
        value: 'false'
      - key: DO_NOT_TRACK
        value: 'true'
      - key: UVICORN_WORKERS
        value: '1'
    disks:
      - name: data
        mountPath: /app/backend/data
        sizeGB: 5

# Optional: Separate worker for background tasks (future use)
# workers:
#   - name: open-webui-worker
#     type: worker
#     env: docker
#     dockerfilePath: ./Dockerfile
#     dockerContext: .
#     build:
#       args:
#         USE_SLIM: 'true'
#     autoDeploy: true
#     envVars:
#       - key: PORT
#         value: '8080'
#     disks:
#       - name: data
#         mountPath: /app/backend/data
#         sizeGB: 5

# Tips:
# 1. Add OPENAI_API_KEY through the Render Dashboard -> Environment section if needed.
# 2. For GPU + CUDA: set USE_CUDA=true and choose a GPU plan + gpuType, may raise costs.
# 3. For external Ollama: set OLLAMA_BASE_URL to the external endpoint and leave USE_OLLAMA=false.
# 4. Increase disk size for large embeddings or Whisper models.
# 5. To force rebuild after model updates, change a dummy build arg or set BUILD_HASH env.

